module.exports = Object.freeze({
  MAX_ADDRESSES_PER_REGISTER: 3,
  MIN_ADDRESSES_PER_REGISTER: 1,
  LOGIN_MIN_LENGTH: 3,
  LOGIN_MAX_LENGTH: 50,
  PASSWORD_MIN_LENGTH: 4,
  PASSWORD_MAX_LENGTH: 200,
  ROLE_MIN_LENGTH: 5,
  ROLE_MAX_LENGTH: 25,
  DEFAULT_ROLE_ON_REGISTER: ["student"],
  VALID_ROLES_TO_REGISTER: ["student", "teacher"],

  EMAIL_ALLOWED_DOMAINS: ["pl", "com", "net", "net.pl", "com.pl"],

  GROUP_SYMBOL_MIN_LENGTH: 2,
  GROUP_SYMBOL_MAX_LENGTH: 10,
});
